### ISSUE TITLE
Can only take off and land once - taking off 2nd time doesn't work

### ISSUE THREAD

**Issue by poshaughnessy** [poshaughnessy/web-bluetooth-parrot-drone#1]
When pressing Take Off again after landing, it gives:

`Uncaught (in promise) DOMException: GATT Service no longer exists.`

**Comment by poshaughnessy** [comment]
For now, need to refresh the page to take off again

**Comment by 360fun** [comment]
Hi, I write here because I'm also playing with the new Bluetooth Web API and I've got the same problem: basically I'm trying to cache the GATT server connection, but when I write some data it executes the command and it disconnects right after! I don't understand if it depends by the device or the API... The trick seems to re-connect every time the GATT server, like you do, but this adds latency and I don't like it: driving drones and robots need a real time response... :'( The weird thing is that the examples provided by Google don't mention this problem and they just cache the characteristic without re-connecting all the time. Sadly the same code doesn't work neither in my Mac or my Android! :( I feel lost...basically when the promise finish, the GATT connection die with it and I've no idea how to keep it alive (without an infinite loop, of course)!

Source:
https://codelabs.developers.google.com/codelabs/candle-bluetooth/#5

**Comment by jyasskin** [comment]
Can both of you capture a BLE trace using the instructions at https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs? That may point out a bug in your javascript, but if it doesn't, please file a bug against Chrome at https://crbug.com/, including that trace.

**Comment by 360fun** [comment]
Nice idea, I'll look into it! Thanks :D

**Comment by poshaughnessy** [comment]
Thanks both of you. I hope to spend some time back on this demo in a few days' time, so I'll hope to help out then if I can.

**Comment by beaufortfrancois** [comment]
I'm trying to figure out what is going on there... 
See my WIP PR at https://github.com/poshaughnessy/web-bluetooth-parrot-drone/pull/7 when debugging
